### ISSUE TITLE
Error in train_graph_cpg.py

### ISSUE THREAD

**Issue by Vunbelievable** [yuzhong-deng/graphcpg#2]
Hi!
Sorry to bother you. I encountered an error when trying to run train_graph_cpg.py. The command I used is as follows:
```
python ${graphcpg}/model/train_graph_cpg.py --dataset_path ${graphcpg}/model/ --dataset HCC
```
However, I received the following error:
```
Traceback (most recent call last):
  File "/public/wangm/software/graphcpg-main//model/train_graph_cpg.py", line 131, in <module>
    trainer.fit(model, datamodule.train_dataloader(), datamodule.val_dataloader())
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run_train
    self._run_sanity_check()
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1267, in _run_sanity_check
    val_loop.run()
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/public/wangm/software/graphcpg-main/model/graphcpg.py", line 135, in validation_step
    y_hat = self(data)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/wangm/software/graphcpg-main/model/graphcpg.py", line 108, in forward
    x = conv(x, edge_index, edge_type)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch_geometric/nn/conv/rgcn_conv.py", line 228, in forward
    segment_count = scatter(torch.ones_like(edge_type), edge_type,
  File "/public/wangm/anaconda3/envs/pytorch/lib/python3.9/site-packages/torch_geometric/utils/_scatter.py", line 75, in scatter
    return src.new_zeros(size).scatter_add_(dim, index, src)
RuntimeError: scatter(): Expected dtype int64 for index
```
Do you have any suggestions? 
Best regards

**Comment by yuzhong-deng** [comment]
Hi, thanks for interested in our work. The error seems to be caused by a data's type not suitble for indexing. However, the main cause could be the incompatibility of packages. Check versions of packages such as torch_geometric and related components may help.
Hope this file [requirements.txt](https://github.com/yuzhong-deng/graphcpg/blob/main/requirements.txt) helps.
